# Generated by Django 2.1.1 on 2018-09-18 10:17

from django.db import migrations

from core.utils import get_unique_slug

SERVERS = [
    {
        "name": "R11",
        "host": "192.168.1.11",
        "port": "3333",
        "miner": "claymores-dual-ethereum-amd-gpu-98",
        "description": "MSI rx470 4g",
    },
    {
        "name": "R12",
        "host": "192.168.1.12",
        "port": "3333",
        "miner": "claymores-dual-ethereum-amd-gpu-98",
        "description": "MSI 1070 8g",
    },
    {
        "name": "R13",
        "host": "192.168.1.13",
        "port": "3333",
        "miner": "claymores-dual-ethereum-amd-gpu-98",
        "description": "Palit 1070 8g",
    },
    {
        "name": "R14",
        "host": "192.168.1.14",
        "port": "3333",
        "miner": "claymores-dual-ethereum-amd-gpu-98",
        "description": "Asus rx570 4g",
    },
    {
        "name": "R15",
        "host": "192.168.1.15",
        "port": "3333",
        "miner": "claymores-dual-ethereum-amd-gpu-98",
        "description": "Asus rx570 4g",
    },
    {
        "name": "R16",
        "host": "192.168.1.16",
        "port": "3333",
        "miner": "claymores-dual-ethereum-amd-gpu-98",
        "description": "Palit 1070 8g",
    },
    {
        "name": "R17",
        "host": "192.168.1.17",
        "port": "3333",
        "miner": "claymores-dual-ethereum-amd-gpu-98",
        "description": "Nitro rx470 8g",
    },
    {
        "name": "R18",
        "host": "192.168.1.18",
        "port": "3333",
        "miner": "claymores-dual-ethereum-amd-gpu-98",
        "description": "Gigabyte rx560 4g",
    },
    {
        "name": "R19",
        "host": "192.168.1.19",
        "port": "3333",
        "miner": "claymores-dual-ethereum-amd-gpu-98",
        "description": "MSI 1070 8g",
    },
    {
        "name": "R21",
        "host": "192.168.1.21",
        "port": "4028",
        "miner": "antminer-s9-cgminer-490",
        "description": "Antminer S9 - 16.8.1.3"
    },
    {
        "name": "R23",
        "host": "192.168.1.23",
        "port": "4028",
        "miner": "antminer-s9-cgminer-490",
        "description": "Antminer S9 - 16.8.1.3"
    },
    {
        "name": "R24",
        "host": "192.168.1.24",
        "port": "4028",
        "miner": "antminer-s9-cgminer-490",
        "description": "Antminer S9 - 16.8.1.3"
    },
    {
        "name": "R25",
        "host": "192.168.1.25",
        "port": "4028",
        "miner": "antminer-s9-cgminer-490",
        "description": "Antminer S9 - 16.8.1.3"
    },
    {
        "name": "R27",
        "host": "192.168.1.27",
        "port": "4028",
        "miner": "antminer-s9-cgminer-490",
        "description": "Antminer S9 - 16.8.1.3"
    },
    {
        "name": "R28",
        "host": "192.168.1.28",
        "port": "4028",
        "miner": "antminer-s9-cgminer-490",
        "description": "Antminer S9 - 16.8.1.3"
    },
    {
        "name": "R29",
        "host": "192.168.1.29",
        "port": "4028",
        "miner": "antminer-s9-cgminer-490",
        "description": "Antminer S9 - 16.8.1.3"
    },
]

def add_server_data(apps, schema_editor):
    Server = apps.get_model('miner', 'Server')
    Miner = apps.get_model('miner', 'Miner')
    for server in SERVERS:
        new_server = Server(
            name=server['name'],
            host=server['host'],
            port=server['port'],
            miner=Miner.objects.get(slug=server['miner']),
            description=server['description'],
        )
        new_server.slug = get_unique_slug(
            new_server,
            'slug',
            'name',
        )
        new_server.save()


def remove_server_data(apps, schema_editor):
    Server = apps.get_model('miner', 'Server')
    for server in SERVERS:
        server_object = Server.objects.get(
            name=server['name'],
        )
        server_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0002_miner_data'),
    ]

    operations = [
        migrations.RunPython(
            add_server_data,
            remove_server_data)
    ]
