# Generated by Django 2.1.1 on 2018-09-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0006_change_help_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('miner', 'slug')},
        ),
    ]
