# Generated by Django 2.1.2 on 2018-10-17 07:32

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0007_miner_request_slug_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miner',
            options={'ordering': ['name', 'version'], 'verbose_name': 'Майнер', 'verbose_name_plural': 'Майнеры'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['miner', 'name'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['name'], 'verbose_name': 'Сервер', 'verbose_name_plural': 'Серверы'},
        ),
        migrations.AlterField(
            model_name='miner',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='miner',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Майнер'),
        ),
        migrations.AlterField(
            model_name='miner',
            name='version',
            field=models.CharField(max_length=31, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='request',
            name='miner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='miner.Miner', verbose_name='Майнер'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request',
            field=models.TextField(max_length=255, validators=[core.validators.validate_json], verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.TextField(blank=True, help_text='Шаблон проверки ответа', validators=[core.validators.validate_json], verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='server',
            name='miner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='miner.Miner', verbose_name='Майнер'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=31, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Порт'),
        ),
    ]
