# Generated by Django 2.1.2 on 2018-10-28 07:42

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0008_add_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miner',
            options={'ordering': ['name', 'version'], 'verbose_name': 'Miner', 'verbose_name_plural': 'Miners'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['miner', 'name'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['name'], 'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
        migrations.AlterField(
            model_name='miner',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='miner',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Miner'),
        ),
        migrations.AlterField(
            model_name='miner',
            name='slug',
            field=models.SlugField(editable=False, help_text='A label for URL config.', max_length=63, unique=True, validators=[core.validators.validate_slug]),
        ),
        migrations.AlterField(
            model_name='miner',
            name='version',
            field=models.CharField(max_length=31, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='request',
            name='miner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='miner.Miner', verbose_name='Miner'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request',
            field=models.TextField(max_length=255, validators=[core.validators.validate_json], verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.TextField(blank=True, help_text='Response template', validators=[core.validators.validate_json], verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='request',
            name='slug',
            field=models.SlugField(editable=False, help_text='A label for URL config.', max_length=31, validators=[core.validators.validate_slug]),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address], verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='server',
            name='miner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='miner.Miner', verbose_name='Miner'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=31, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='server',
            name='slug',
            field=models.SlugField(editable=False, help_text='A label for URL config.', max_length=31, unique=True, validators=[core.validators.validate_slug]),
        ),
    ]
