# Generated by Django 2.1.1 on 2018-10-12 07:17

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0013_rename_server_task_field_last_executed_to_executed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField(help_text='Идентификатор опроса', validators=[django.core.validators.MinValueValidator(1)])),
                ('result', models.TextField(help_text='Результат выполнения задания', validators=[core.validators.validate_json])),
                ('executed', models.DateTimeField(help_text='Время выполнения задания')),
                ('status', models.BooleanField(help_text='Статус выполнения задания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='task.ServerTask')),
            ],
            options={
                'verbose_name': 'Статистика работы серверов',
                'ordering': ['-request_id', 'task', '-status'],
            },
        ),
    ]
