# Generated by Django 2.1.2 on 2018-10-17 07:32

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverstatistic',
            options={'ordering': ['-request_id', 'task', '-status'], 'verbose_name': 'Статистика сервера', 'verbose_name_plural': 'Статистика серверов'},
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='executed',
            field=models.DateTimeField(verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='result',
            field=models.TextField(validators=[core.validators.validate_json], verbose_name='Результат опроса'),
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='status',
            field=models.BooleanField(verbose_name='Статус завершения'),
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='task.ServerTask', verbose_name='Задание'),
        ),
    ]
