# Generated by Django 2.1.2 on 2018-10-28 07:42

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_add_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverstatistic',
            options={'ordering': ['-request_id', 'task', '-status'], 'verbose_name': 'Server statistic', 'verbose_name_plural': 'Servers statistics'},
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='executed',
            field=models.DateTimeField(verbose_name='Executed at'),
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='request_id',
            field=models.IntegerField(help_text='Request ID', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='result',
            field=models.TextField(validators=[core.validators.validate_json], verbose_name='Request result'),
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='status',
            field=models.BooleanField(verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='serverstatistic',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='task.ServerTask', verbose_name='Task'),
        ),
    ]
