# Generated by Django 2.1.1 on 2018-09-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_config_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-enabled', 'name'], 'verbose_name': 'Конфигурация'},
        ),
    ]
