# Generated by Django 2.1.1 on 2018-09-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_server_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-enabled', 'server'], 'verbose_name': 'Опрос сервера'},
        ),
    ]
