# Generated by Django 2.1.1 on 2018-09-27 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_allow_null_zabbix_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='log_file',
            field=models.CharField(blank=True, max_length=4096, validators=[django.core.validators.RegexValidator(message='Путь к файлу должен соответствовать POSIX', regex='^/[^\\0]*[^\\0/]+$')]),
        ),
    ]
