# Generated by Django 2.1.1 on 2018-10-04 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_file_log_POSIX_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='zabbix_timeout',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
