# Generated by Django 2.1.1 on 2018-10-04 05:15

from django.db import migrations

def add_config_data(apps, schema_editor):
    Config = apps.get_model('task', 'Config')

    develop = Config.objects.get(name='Develop')
    develop.zabbix_port = None
    develop.save()

    default = Config.objects.get(name='Default')
    default.zabbix_timeout = 5
    default.save()

def remove_config_data(apps, schema_editor):
    Config = apps.get_model('task', 'Config')

    develop = Config.objects.get(name='Develop')
    develop.zabbix_port = 10051
    develop.save()

    default = Config.objects.get(name='Default')
    default.zabbix_timeout = None
    default.save()

class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_config_add_zabbix_timeout'),
    ]

    operations = [
        migrations.RunPython(
            add_config_data,
            remove_config_data)
    ]
