# Generated by Django 2.1.1 on 2018-10-04 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_config_data_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
