# Generated by Django 2.1.1 on 2018-10-08 13:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('miner', '0007_miner_request_slug_unique_together'),
        ('task', '0011_server_add_timeout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server',
            new_name='ServerTask',
        ),
    ]
