# Generated by Django 2.1.1 on 2018-10-07 20:49

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_server_add_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(help_text='Результат выполнения опроса', validators=[core.validators.validate_json])),
                ('executed', models.DateTimeField(help_text='Время выполнения опроса')),
                ('status', models.BooleanField(help_text='Статус опроса')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistic', to='task.Server')),
            ],
            options={
                'verbose_name': 'Статистика работы серверов',
                'ordering': ['executed', 'server', '-status'],
            },
        ),
    ]
