# Generated by Django 2.1.1 on 2018-10-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_rename_server_to_server_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servertask',
            name='last_executed',
        ),
        migrations.AddField(
            model_name='servertask',
            name='executed',
            field=models.DateTimeField(help_text='Время последнего запуска', null=True),
        ),
    ]
