# Generated by Django 2.1.1 on 2018-10-10 05:56

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_rename_server_to_server_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField(help_text='Идентификатор опроса', validators=[django.core.validators.MinValueValidator(1)])),
                ('result', models.TextField(help_text='Результат выполнения задания', validators=[core.validators.validate_json])),
                ('executed', models.DateTimeField(help_text='Время выполнения задания')),
                ('status', models.BooleanField(help_text='Статус выполнения задания')),
            ],
            options={
                'verbose_name': 'Статистика работы серверов',
                'ordering': ['-request_id', 'task', '-status'],
            },
        ),
        migrations.RemoveField(
            model_name='servertask',
            name='last_executed',
        ),
        migrations.AddField(
            model_name='servertask',
            name='executed',
            field=models.DateTimeField(help_text='Время последнего запуска', null=True),
        ),
        migrations.AddField(
            model_name='serverstatistic',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='task.ServerTask'),
        ),
    ]
