# Generated by Django 2.1.2 on 2018-10-17 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_rename_server_task_field_last_executed_to_executed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-enabled', 'name'], 'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='servertask',
            options={'ordering': ['-enabled', 'server'], 'verbose_name': 'Опрос сервера', 'verbose_name_plural': 'Опросы серверов'},
        ),
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='config',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='config',
            name='log',
            field=models.CharField(choices=[('NO', 'Выключить'), ('SY', 'Системный журнал'), ('ST', 'Консоль'), ('FI', 'Файл')], default='SY', max_length=2, verbose_name='Лог'),
        ),
        migrations.AlterField(
            model_name='config',
            name='log_file',
            field=models.CharField(blank=True, max_length=4096, validators=[django.core.validators.RegexValidator(message='Путь к файлу должен соответствовать POSIX', regex='^/[^\\0]*[^\\0/]+$')], verbose_name='Файл лога'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=31, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='config',
            name='refresh',
            field=models.PositiveSmallIntegerField(default=30, help_text='Интервал опроса серверов (сек.).', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Интервал опроса серверов'),
        ),
        migrations.AlterField(
            model_name='config',
            name='zabbix_port',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Порт Zabbix сервера'),
        ),
        migrations.AlterField(
            model_name='config',
            name='zabbix_send',
            field=models.BooleanField(default=False, verbose_name='Отправлять статистику Zabbix'),
        ),
        migrations.AlterField(
            model_name='config',
            name='zabbix_server',
            field=models.GenericIPAddressField(blank=True, null=True, validators=[django.core.validators.validate_ipv46_address], verbose_name='Адрес Zabbix сервера'),
        ),
        migrations.AlterField(
            model_name='config',
            name='zabbix_timeout',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Таймаут Zabbix сервера'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='executed',
            field=models.DateTimeField(null=True, verbose_name='Последний запуск'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='requests',
            field=models.ManyToManyField(related_name='tasks', to='miner.Request', verbose_name='Запросы'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='miner.Server', verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Таймаут'),
        ),
    ]
