# Generated by Django 2.1.2 on 2018-10-28 07:42

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_add_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-enabled', 'name'], 'verbose_name': 'Configuration', 'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterModelOptions(
            name='servertask',
            options={'ordering': ['-enabled', 'server'], 'verbose_name': 'Server request', 'verbose_name_plural': 'Servers requests'},
        ),
        migrations.AlterField(
            model_name='config',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='config',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='config',
            name='log',
            field=models.CharField(choices=[('NO', 'Disabled'), ('SY', 'Systemd journal'), ('ST', 'STDOUT'), ('FI', 'File')], default='SY', max_length=2, verbose_name='Log'),
        ),
        migrations.AlterField(
            model_name='config',
            name='log_file',
            field=models.CharField(blank=True, max_length=4096, validators=[django.core.validators.RegexValidator(message='Path to the file must follow POSIX', regex='^/[^\\0]*[^\\0/]+$')], verbose_name='Log file'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=31, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='config',
            name='refresh',
            field=models.PositiveSmallIntegerField(default=30, help_text='Request interval (sec.).', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Request interval'),
        ),
        migrations.AlterField(
            model_name='config',
            name='slug',
            field=models.SlugField(editable=False, help_text='A label for URL config.', max_length=63, unique=True, validators=[core.validators.validate_slug]),
        ),
        migrations.AlterField(
            model_name='config',
            name='zabbix_port',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Zabbix port'),
        ),
        migrations.AlterField(
            model_name='config',
            name='zabbix_send',
            field=models.BooleanField(default=False, verbose_name='Send statistic to Zabbix'),
        ),
        migrations.AlterField(
            model_name='config',
            name='zabbix_server',
            field=models.GenericIPAddressField(blank=True, null=True, validators=[django.core.validators.validate_ipv46_address], verbose_name='Zabbix host'),
        ),
        migrations.AlterField(
            model_name='config',
            name='zabbix_timeout',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Zabbix timeout'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='executed',
            field=models.DateTimeField(null=True, verbose_name='Last executed'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='requests',
            field=models.ManyToManyField(related_name='tasks', to='miner.Request', verbose_name='Requests'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='miner.Server', verbose_name='Server'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Last status'),
        ),
        migrations.AlterField(
            model_name='servertask',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Timeout'),
        ),
    ]
